use chrono::NaiveDateTime;
use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};
use sqlx::FromRow;

#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct User {
    pub id: i64,
    pub email: String,
    pub username: String,
    pub password: String,
    pub first_name: String,
    pub last_name: String,
    pub description: Option<String>,
    pub phone_number: Option<String>,
    pub avatar_id: Option<i64>,
    pub language: String,
    pub locker_id: Option<i64>,
    pub stripe_customer_id: Option<String>,
    pub stripe_connect_account_id: Option<String>,
    pub stripe_connect_status: Option<String>,
    pub stripe_connect_charges_enabled: bool,
    pub stripe_connect_payouts_enabled: bool,
    pub stripe_connect_onboarded_at: Option<NaiveDateTime>,
    pub privacy_policy_accepted: bool,
    pub terms_of_service_accepted: bool,
    pub marketing_emails_accepted: bool,
    pub consents_accepted_at: Option<NaiveDateTime>,
    pub google_id: Option<String>,
    pub facebook_id: Option<String>,
    pub social_provider: Option<String>,
    pub social_provider_id: Option<String>,
    pub average_rating: Option<Decimal>,
    pub review_count: i32,
    pub activation_code_expires_at: Option<NaiveDateTime>,
    pub last_unread_notification_at: Option<NaiveDateTime>,
    pub preferred_item_types: Option<String>,
    pub default_inpost_locker: Option<String>,
    pub email_verified_at: Option<NaiveDateTime>,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

/// User model without the password field, safe for API responses.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct UserSafe {
    pub id: i64,
    pub email: String,
    pub username: String,
    pub first_name: String,
    pub last_name: String,
    pub description: Option<String>,
    pub phone_number: Option<String>,
    pub avatar_id: Option<i64>,
    pub language: String,
    pub locker_id: Option<i64>,
    pub stripe_customer_id: Option<String>,
    pub stripe_connect_account_id: Option<String>,
    pub stripe_connect_status: Option<String>,
    pub stripe_connect_charges_enabled: bool,
    pub stripe_connect_payouts_enabled: bool,
    pub stripe_connect_onboarded_at: Option<NaiveDateTime>,
    pub privacy_policy_accepted: bool,
    pub terms_of_service_accepted: bool,
    pub marketing_emails_accepted: bool,
    pub consents_accepted_at: Option<NaiveDateTime>,
    pub google_id: Option<String>,
    pub facebook_id: Option<String>,
    pub social_provider: Option<String>,
    pub social_provider_id: Option<String>,
    pub average_rating: Option<Decimal>,
    pub review_count: i32,
    pub activation_code_expires_at: Option<NaiveDateTime>,
    pub last_unread_notification_at: Option<NaiveDateTime>,
    pub preferred_item_types: Option<String>,
    pub default_inpost_locker: Option<String>,
    pub email_verified_at: Option<NaiveDateTime>,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

impl From<User> for UserSafe {
    fn from(user: User) -> Self {
        Self {
            id: user.id,
            email: user.email,
            username: user.username,
            first_name: user.first_name,
            last_name: user.last_name,
            description: user.description,
            phone_number: user.phone_number,
            avatar_id: user.avatar_id,
            language: user.language,
            locker_id: user.locker_id,
            stripe_customer_id: user.stripe_customer_id,
            stripe_connect_account_id: user.stripe_connect_account_id,
            stripe_connect_status: user.stripe_connect_status,
            stripe_connect_charges_enabled: user.stripe_connect_charges_enabled,
            stripe_connect_payouts_enabled: user.stripe_connect_payouts_enabled,
            stripe_connect_onboarded_at: user.stripe_connect_onboarded_at,
            privacy_policy_accepted: user.privacy_policy_accepted,
            terms_of_service_accepted: user.terms_of_service_accepted,
            marketing_emails_accepted: user.marketing_emails_accepted,
            consents_accepted_at: user.consents_accepted_at,
            google_id: user.google_id,
            facebook_id: user.facebook_id,
            social_provider: user.social_provider,
            social_provider_id: user.social_provider_id,
            average_rating: user.average_rating,
            review_count: user.review_count,
            activation_code_expires_at: user.activation_code_expires_at,
            last_unread_notification_at: user.last_unread_notification_at,
            preferred_item_types: user.preferred_item_types,
            default_inpost_locker: user.default_inpost_locker,
            email_verified_at: user.email_verified_at,
            created_at: user.created_at,
            updated_at: user.updated_at,
        }
    }
}
